#!/usr/bin/env oo-ruby

#   Copyright 2014 Red Hat Inc.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
# Purpose: Runs oo-accept-node and reports the results
require 'tempfile'
require 'syslog'

class AcceptNode
  attr_accessor :output, :verbose, :exitcode

  @@accept_node = '/usr/sbin/oo-accept-node'

  def initialize(verbose=false)
    @verbose = verbose
  end

  def run
    tmpfile = Tempfile.new(self.class.name)

    if @verbose
      cmd = "/usr/bin/env oo-ruby -E UTF-8:UTF-8 #{@@accept_node} -v 2>&1 | /usr/bin/tee #{tmpfile.path} ; exit ${PIPESTATUS[0]}"
    else
      cmd = "/usr/bin/env oo-ruby -E UTF-8:UTF-8 #{@@accept_node} -v > #{tmpfile.path} 2>&1"
    end

    system(cmd)
    @exitcode = $?.exitstatus
    @output = File.read(tmpfile.path)
  end
end


def main
  if File.exists?('/var/lock/openshift_update_in_progress')
    return
  end

  an = AcceptNode.new()
  an.run() # run oo-accept-node

  if an.exitcode != 0
    log  = Syslog.open('openshift-node-accept', Syslog::LOG_PID, Syslog::LOG_USER)
    an.output.each_line do |line|
      log.info(line)
    end
    log.close
  end
end

if __FILE__ == $0
  main
end
