#!/usr/bin/env oo-ruby
#
#   Copyright 2014 Red Hat Inc.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
# Purpose: report district capacity statistics
#
require 'syslog'

load '/usr/sbin/oo-stats'

def get_district_stats
  begin
    stats = OOStats.new
    stats.gather_statistics
    return stats.results
  rescue => e
    $log.puts e.message
    $log.puts e.backtrace
  end

  return nil
end

def main
  stats = get_district_stats

  if stats.nil?
    $log.error "Unable to gather stats from oo-stats. Exiting..."
    exit
  end

  stats['profile_summaries'].each do |profile|
    name        = profile['profile']
    total_gears = profile['gears_total_count']
    active_gears = profile['gears_active_count']
    avail_gears = profile['effective_available_gears']
    avail_uids  = profile['dist_avail_uids']

    $log.info "src=osemetric scope=district component=gears name=#{name} total=#{total_gears} active=#{active_gears} available=#{avail_gears} available-uids=#{avail_uids}"
  end
end

if __FILE__ == $0
  $log  = Syslog.open('openshift-check', Syslog::LOG_PID, Syslog::LOG_USER)
  $log.close
  main
end
